### ISSUE TITLE
Transparent parts too transparent in PLI

### ISSUE THREAD

**Issue by mfeldt** [LasseD/buildinginstructions.js#44]
**Describe the bug**
In the PLI section, transparent parts are practically invisible. This was not the case in earlier versions.

**To Reproduce**
1. Make a model with transparent parts
2. Look at the PLI
3. See nothing

![tp_new_version](https://user-images.githubusercontent.com/1193964/107344787-25c88f80-6ac3-11eb-9ed6-8136a26bd324.png)

**Expected behavior**
I expected to see transparent parts as in the version from about one year ago

![tp_old_version](https://user-images.githubusercontent.com/1193964/107344789-26612600-6ac3-11eb-89a5-550f7637c972.png)

**Device (please complete the following information):**
 - Windows 10 / Android 10
 - firefox, chrome, android webview

**Comment by LasseD** [comment]
Hi @mfeldt. Do you see any error messages in the console, and what happens when you click the line contrast button in options?


The lines in your transparent parts look white, which seems incorrect. Trans-clear should show dark lines:

LDR.Colors[47] = {name:'Trans_Clear', value:0xFCFCFC, edge:0xC9C9C9, ...};

The color of parts you looks more like the new trans sticker color:

LDR.Colors[10047] = {name:'Trans_Sticker', value:0xFFFFFF, edge:0xFFFFFF, alpha:16};

Which color is shown when you click the parts and see the part view?

**Comment by mfeldt** [comment]
There are no errors in the console. I can click on th eemtpy space where the part is supposed to be, and then the detailed preview appears with the outline *just* visible (see attachment).


![ppview](https://user-images.githubusercontent.com/1193964/107491623-b1a5ee80-6b8b-11eb-9caa-74ee526d47c6.png)


In the options section, I can press the outline button and then all parts (including the transparent ones) will show enhanced outlines.

**Comment by LasseD** [comment]
Issue reproduced locally. It was caused by edge lines being drawn with alpha enabled, causing them to be near invisible.
